eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9011
spring:
  application:
    name: account
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.26.128:3306/account_db?useSSL=false
    #url: jdbc:mysql://192.168.121.5:3306/account_db?useSSL=false
    username: root
    password: root
mybatis:
  typeAliasesPackage: com.lzh.account.model.entity,com.lzh.common.model.entity.account
  mapperLocations: classpath:mapper/*Mapper.xml